const InformationSecurityWithHelmetJSModuleNames=[
    "Install and Require Helmet",
    "Hide Potentially Dangerous Information Using helmet.hidePoweredBy()",
    "Mitigate the Risk of Clickjacking with helmet.frameguard()",
    "Mitigate the Risk of Cross Site Scripting (XSS) Attacks with helmet.xssFilter()",
    "Avoid Inferring the Response MIME Type with helmet.noSniff()",
    "Prevent IE from Opening Untrusted HTML with helmet.ieNoOpen()",
    "Ask Browsers to Access Your Site via HTTPS Only with helmet.hsts()",
    "Disable DNS Prefetching with helmet.dnsPrefetchControl()",
    "Disable Client-Side Caching with helmet.noCache()",
    "Set a Content Security Policy with helmet.contentSecurityPolicy()",
    "Configure Helmet Using the ‘parent’ helmet() Middleware",
    "Understand BCrypt Hashes",
    "Hash and Compare Passwords Asynchronously",
    "Hash and Compare Passwords Synchronously",
]

const QualityAssuranceAndTestingWithChaiModuleNames =[
    "Learn How JavaScript Assertions Work",
"Test if a Variable or Function is Defined",
"Use Assert.isOK and Assert.isNotOK",
"Test for Truthiness",
"Use the Double Equals to Assert Equality",
"Use the Triple Equals to Assert Strict Equality",
"Assert Deep Equality with .deepEqual and .notDeepEqual",
"Compare the Properties of Two Elements",
"Test if One Value is Below or At Least as Large as Another",
"Test if a Value Falls within a Specific Range",
"Test if a Value is an Array",
"Test if an Array Contains an Item",
"Test if a Value is a String",
"Test if a String Contains a Substring",
"Use Regular Expressions to Test a String",
"Test if an Object has a Property",
"Test if a Value is of a Specific Data Structure Type",
"Test if an Object is an Instance of a Constructor",
"Run Functional Tests on API Endpoints using Chai-HTTP",
"Run Functional Tests on API Endpoints using Chai-HTTP II",
"Run Functional Tests on an API Response using Chai-HTTP III - PUT method",
"Run Functional Tests on an API Response using Chai-HTTP IV - PUT method",
"Run Functional Tests using a Headless Browser",
"Run Functional Tests using a Headless Browser II"
]
const AdvancedNodeandExpressModuleNames =[
    "Set up a Template Engine",
"Use a Template Engine's Powers",
"Set up Passport",
"Serialization of a User Object",
"Implement the Serialization of a Passport User",
"Authentication Strategies",
"How to Use Passport Strategies",
"Create New Middleware",
"How to Put a Profile Together",
"Logging a User Out",
"Registration of New Users",
"Hashing Your Passwords",
"Clean Up Your Project with Modules",
"Implementation of Social Authentication",
"Implementation of Social Authentication II",
"Implementation of Social Authentication III",
"Set up the Environment",
"Communicate by Emitting",
"Handle a Disconnect",
"Authentication with Socket.IO",
"Announce New Users",
"Send and Display Chat Messages"
]