const ES6ModuleNames=[
    "Explore Differences Between the var and let Keywords",
    "Compare Scopes of the var and let Keywords",
    "Declare a Read-Only Variable with the const Keyword",
    "Mutate an Array Declared with const",
    "Prevent Object Mutation",
    "Use Arrow Functions to Write Concise Anonymous Functions",
    "Write Arrow Functions with Parameters",
    "Write Higher-Order Arrow Functions",
    "Set Default Parameters for Your Functions",
    "Use the Rest Operator with Function Parameters",
    "Use the Spread Operator to Evaluate Arrays In-Place",
    "Use Destructuring Assignment to Assign Variables from Objects",
    "Use Destructuring Assignment to Assign Variables from Nested Objects",
    "Use Destructuring Assignment to Assign Variables from Arrays",
    "Use Destructuring Assignment with the Rest Operator to Reassign Array Elements",
    "Use Destructuring Assignment to Pass an Object as a Function\"s Parameters",
    "Create Strings using Template Literals",
    "Write Concise Object Literal Declarations Using Simple Fields",
    "Write Concise Declarative Functions with ES6",
    "Use class Syntax to Define a Constructor Function",
    "Use getters and setters to Control Access to an Object",
    "Understand the Differences Between import and require",
    "Use export to Reuse a Code Block",
    "Use * to Import Everything from a File",
    "Create an Export Fallback with export default",
    "Import a Default Export"
    ]